variables:
  IMAGE_NAME: droneus/nginx-http-server
  VERSION_FILE: version.txt

stages:
  - build

build_image:
  stage: build
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - ls -la
    - ls -la scripts/*
    - ./scripts/update_version.sh increment version.txt
    - VERSION=$(cat "$VERSION_FILE")
    - docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker push $IMAGE_NAME:latest 
    - docker push $IMAGE_NAME:$VERSION
