apiVersion: apps/v1
kind: Deployment
metadata:
  name: vivus-with-ascii
  namespace: vivus-with-ascii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vivus-with-ascii-app
  template:
    metadata:
      labels:
        app:  vivus-with-ascii-app
    spec:
      containers:
      - name: vivus-with-asciis-container
        #  image: droneus/nginx-http-server:latest
        image: droneus/vivo-ascii
        ports:
        - containerPort: 8000
