apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-types
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-types-app
  template:
    metadata:
      labels:
        app: devops-types-app
    spec:
      containers:
      - name: devops-types-container
        image: droneus/nginx-http-server:latest
        ports:
        - containerPort: 80
