apiVersion: v1
kind: Service
metadata:
  name: devops-types-service
spec:
  type: NodePort
  selector:
    app: devops-types-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000  # Optional: Specify a nodePort in the range 30000-32767 if you want a specific port
