apiVersion: v1
kind: Service
metadata:
  name: vivus-with-ascii-app
  namespace: vivus-with-ascii
spec:
  type: NodePort
  selector:
    app:  vivus-with-ascii-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30300  # Optional: Specify a nodePort in the range 30000-32767 if you want a specific port
